---
title: "Final_Project"
author: "Rolando Santos"
date: "2023-11-26"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(forcats)
library(ggplot2)
library(gridExtra)
library(cowplot)
```

```{r}
bike_sharing <- read.csv("day.csv")
head(bike_sharing)
```

```{r}
dim(bike_sharing)
```

```{r}
na_count <-sapply(bike_sharing, function(y) sum(is.na(y))) 
na_count <- data.frame(na_count)
na_count
```

There are no NAs in the the dataset.

### Data Cleaning

```{r}
bike_sharing <- bike_sharing[ ,!names(bike_sharing) %in% c("instant", "registered", "dteday", "casual")]
head(bike_sharing)
```

```{r}
bike_sharing <- bike_sharing %>% 
  rename(
    year = yr,
    month = mnth,
  )

bike_sharing <- bike_sharing %>% mutate(
  holiday = fct_recode(as.factor(holiday),
    "No" = "0",
    "Yes" = "1",
  )
) %>% mutate(
  season = fct_recode(as.factor(season),
    "Spring" = "1",
    "Summer" = "2",
    "Fall" = "3",
    "Winter" = "4"
  )
) %>% mutate(
  year = fct_recode(as.factor(year),
    "2011" = "0",
    "2012" = "1"
  )
) %>% mutate(
  month = fct_recode(as.factor(month),
    "January" = "1",
    "February" = "2",
    "March" = "3",
    "April" = "4",
    "May" = "5",
    "June" = "6",
    "July" = "7",
    "August" = "8",
    "September" = "9",
    "October" = "10",
    "November" = "11",
    "December" = "12"
  )
) %>% mutate(
  weekday = fct_recode(as.factor(weekday),
    "Sunday" = "0",
    "Monday" = "1",
    "Tuesday" = "2",
    "Wednesday" = "3",
    "Thursday" = "4",
    "Friday" = "5",
    "Saturday" = "6"
  )
) %>% mutate(
  workingday = fct_recode(as.factor(workingday),
    "No" = "0",
    "Yes" = "1"
  )
) %>% mutate(
  weathersit = fct_recode(as.factor(weathersit),
    "Clear" = "1",
    "Misty" = "2",
    "Snow/Rain" = "3"
  )
)
head(bike_sharing)
```

```{r}
model <- lm(cnt ~ ., data = bike_sharing)
summary(model)
```

```{r}
create_bp <- function(var){
  bike_sharing %>%
    ggplot(
      aes_string(x = toString(var), y = "cnt", fill = "year")
    ) + geom_col(
      position = position_dodge()
    )
}



plot_grid(
  create_bp("season"), 
  create_bp("weathersit"),
  create_bp("holiday"),
  create_bp("month"),
  labels=c("A", "B"),
  ncol = 2, nrow = 2)
```
